# Generated by Django 4.1.3 on 2025-03-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('study', 'Çalışma Kafesi'), ('family', 'Aile Kafesi'), ('romantic', 'Romantik Mekan'), ('casual', 'Sıradan Kafe')], max_length=20)),
                ('rating', models.FloatField(default=0.0)),
                ('total_reviews', models.IntegerField(default=0)),
            ],
        ),
    ]
