# Generated by Django 5.2 on 2025-04-07 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='has_wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='price_range',
            field=models.CharField(choices=[('cheap', 'Uygun'), ('medium', 'Orta'), ('expensive', 'Pahalı')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('study', 'Çalışma Kafesi'), ('family', 'Aile Kafesi'), ('romantic', 'Romantik Mekan'), ('casual', 'Sıradan Kafe'), ('luxury', 'Lüks Kafe'), ('outdoor', 'Açık Hava Mekanı'), ('vegan', 'Vegan Dostu Kafe'), ('pet_friendly', 'Evcil Hayvan Dostu'), ('breakfast', 'Kahvaltı Mekanı'), ('dessert', 'Tatlıcı / Pastane'), ('book_cafe', 'Kitap Kafesi'), ('cozy', 'Samimi ve Sakin Mekan'), ('fast_food', 'Hızlı Yemek'), ('themed', 'Tematik Kafe'), ('music', 'Canlı Müzikli Mekan')], max_length=20),
        ),
        migrations.CreateModel(
            name='FavoritePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='core.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'place')},
            },
        ),
    ]
